// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAgentByID = `-- name: FindAgentByID :one
SELECT id, created_at
FROM agents
WHERE id = $1
`

func (q *Queries) FindAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, findAgentByID, id)
	var i Agent
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
