// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findContactByExternalContactID = `-- name: FindContactByExternalContactID :one
SELECT id, external_contact_id, created_at
FROM contacts
WHERE external_contact_id = $1
`

func (q *Queries) FindContactByExternalContactID(ctx context.Context, externalContactID string) (Contact, error) {
	row := q.db.QueryRow(ctx, findContactByExternalContactID, externalContactID)
	var i Contact
	err := row.Scan(&i.ID, &i.ExternalContactID, &i.CreatedAt)
	return i, err
}

const findContactByID = `-- name: FindContactByID :one
SELECT id, external_contact_id, created_at
FROM contacts
WHERE id = $1
`

func (q *Queries) FindContactByID(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, findContactByID, id)
	var i Contact
	err := row.Scan(&i.ID, &i.ExternalContactID, &i.CreatedAt)
	return i, err
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (id, external_contact_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    external_contact_id = EXCLUDED.external_contact_id
`

type UpsertContactParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalContactID string             `json:"external_contact_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.Exec(ctx, upsertContact, arg.ID, arg.ExternalContactID, arg.CreatedAt)
	return err
}
