// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findConversationWithContactUnreadMessagesByID = `-- name: FindConversationWithContactUnreadMessagesByID :one
SELECT id, status, agent_id, contact_id, created_at, updated_at, finished_at
FROM conversations
WHERE id = $1
`

func (q *Queries) FindConversationWithContactUnreadMessagesByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationWithContactUnreadMessagesByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AgentID,
		&i.ContactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findConversationWithoutMessages = `-- name: FindConversationWithoutMessages :one
SELECT id, status, agent_id, contact_id, created_at, updated_at, finished_at
FROM conversations
WHERE id = $1
`

func (q *Queries) FindConversationWithoutMessages(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, findConversationWithoutMessages, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AgentID,
		&i.ContactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const findOpenConversationWithMessageExternalIDsByContactID = `-- name: FindOpenConversationWithMessageExternalIDsByContactID :one
SELECT id, status, agent_id, contact_id, created_at, updated_at, finished_at
FROM conversations
WHERE contact_id = $1
  AND status IN ('pending', 'assigned')
LIMIT 1
`

func (q *Queries) FindOpenConversationWithMessageExternalIDsByContactID(ctx context.Context, contactID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, findOpenConversationWithMessageExternalIDsByContactID, contactID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.AgentID,
		&i.ContactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const upsertConversation = `-- name: UpsertConversation :exec
INSERT INTO conversations (id, status, agent_id, contact_id, created_at, updated_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    agent_id = EXCLUDED.agent_id,
    contact_id = EXCLUDED.contact_id,
    updated_at = EXCLUDED.updated_at,
    finished_at = EXCLUDED.finished_at
`

type UpsertConversationParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.Exec(ctx, upsertConversation,
		arg.ID,
		arg.Status,
		arg.AgentID,
		arg.ContactID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	return err
}
