// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findMessageByExternalID = `-- name: FindMessageByExternalID :one
SELECT id, conversation_id, status, type, text, user_id, contact_id, external_id, sent_at, read_at, edited_at, deleted_at
FROM messages
WHERE external_id = $1
`

func (q *Queries) FindMessageByExternalID(ctx context.Context, externalID *string) (Message, error) {
	row := q.db.QueryRow(ctx, findMessageByExternalID, externalID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Type,
		&i.Text,
		&i.UserID,
		&i.ContactID,
		&i.ExternalID,
		&i.SentAt,
		&i.ReadAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listConversationMessagesPage = `-- name: ListConversationMessagesPage :many
SELECT
    id,
    status,
    type,
    text,
    user_id,
    contact_id,
    sent_at,
    read_at,
    edited_at,
    deleted_at
FROM messages
WHERE conversation_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (sent_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY sent_at DESC, id DESC
LIMIT $4::int + 1
`

type ListConversationMessagesPageParams struct {
	ConversationID pgtype.UUID
	BeforeSentAt   pgtype.Timestamptz
	BeforeID       pgtype.UUID
	PageSize       int32
}

type ListConversationMessagesPageRow struct {
	ID        pgtype.UUID
	Status    string
	Type      string
	Text      *string
	UserID    pgtype.UUID
	ContactID pgtype.UUID
	SentAt    pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
	EditedAt  pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) ListConversationMessagesPage(ctx context.Context, arg ListConversationMessagesPageParams) ([]ListConversationMessagesPageRow, error) {
	rows, err := q.db.Query(ctx, listConversationMessagesPage,
		arg.ConversationID,
		arg.BeforeSentAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationMessagesPageRow{}
	for rows.Next() {
		var i ListConversationMessagesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Type,
			&i.Text,
			&i.UserID,
			&i.ContactID,
			&i.SentAt,
			&i.ReadAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesWithExternalIDByConversation = `-- name: ListMessagesWithExternalIDByConversation :many
SELECT id, conversation_id, status, type, text, user_id, contact_id, external_id, sent_at, read_at, edited_at, deleted_at
FROM messages
WHERE conversation_id = $1
  AND external_id IS NOT NULL
ORDER BY sent_at, id
`

func (q *Queries) ListMessagesWithExternalIDByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesWithExternalIDByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Status,
			&i.Type,
			&i.Text,
			&i.UserID,
			&i.ContactID,
			&i.ExternalID,
			&i.SentAt,
			&i.ReadAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadContactMessagesByConversation = `-- name: ListUnreadContactMessagesByConversation :many
SELECT id, conversation_id, status, type, text, user_id, contact_id, external_id, sent_at, read_at, edited_at, deleted_at
FROM messages
WHERE conversation_id = $1
  AND contact_id IS NOT NULL
  AND read_at IS NULL
ORDER BY sent_at, id
`

func (q *Queries) ListUnreadContactMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listUnreadContactMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Status,
			&i.Type,
			&i.Text,
			&i.UserID,
			&i.ContactID,
			&i.ExternalID,
			&i.SentAt,
			&i.ReadAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages (id, conversation_id, status, type, text, user_id, contact_id, external_id, sent_at, read_at, edited_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    type = EXCLUDED.type,
    text = EXCLUDED.text,
    user_id = EXCLUDED.user_id,
    contact_id = EXCLUDED.contact_id,
    external_id = EXCLUDED.external_id,
    sent_at = EXCLUDED.sent_at,
    read_at = EXCLUDED.read_at,
    edited_at = EXCLUDED.edited_at,
    deleted_at = EXCLUDED.deleted_at
`

type UpsertMessageParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Status         string
	Type           string
	Text           *string
	UserID         pgtype.UUID
	ContactID      pgtype.UUID
	ExternalID     *string
	SentAt         pgtype.Timestamptz
	ReadAt         pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.Exec(ctx, upsertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Status,
		arg.Type,
		arg.Text,
		arg.UserID,
		arg.ContactID,
		arg.ExternalID,
		arg.SentAt,
		arg.ReadAt,
		arg.EditedAt,
		arg.DeletedAt,
	)
	return err
}
