// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalContactID string             `json:"external_contact_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Status         string             `json:"status"`
	Type           string             `json:"type"`
	Text           *string            `json:"text"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	ContactID      pgtype.UUID        `json:"contact_id"`
	ExternalID     *string            `json:"external_id"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}
