// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAgentByID = `-- name: FindAgentByID :one
SELECT a.id, a.name, a.email, a.created_at
FROM agents a
WHERE a.id = $1
`

type FindAgentByIDRow struct {
	Agent Agent `json:"agent"`
}

func (q *Queries) FindAgentByID(ctx context.Context, id pgtype.UUID) (FindAgentByIDRow, error) {
	row := q.db.QueryRow(ctx, findAgentByID, id)
	var i FindAgentByIDRow
	err := row.Scan(
		&i.Agent.ID,
		&i.Agent.Name,
		&i.Agent.Email,
		&i.Agent.CreatedAt,
	)
	return i, err
}
