// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findContactByExternalID = `-- name: FindContactByExternalID :one
SELECT c.id, c.external_contact_id, c.created_at
FROM contacts c
WHERE c.external_contact_id = $1
`

type FindContactByExternalIDRow struct {
	Contact Contact `json:"contact"`
}

func (q *Queries) FindContactByExternalID(ctx context.Context, externalContactID string) (FindContactByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findContactByExternalID, externalContactID)
	var i FindContactByExternalIDRow
	err := row.Scan(&i.Contact.ID, &i.Contact.ExternalContactID, &i.Contact.CreatedAt)
	return i, err
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (id, external_contact_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    external_contact_id = EXCLUDED.external_contact_id
`

type UpsertContactParams struct {
	ID                pgtype.UUID        `json:"id"`
	ExternalContactID string             `json:"external_contact_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.Exec(ctx, upsertContact, arg.ID, arg.ExternalContactID, arg.CreatedAt)
	return err
}
