// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertMessages = `-- name: BatchUpsertMessages :exec
INSERT INTO messages (id, conversation_id, external_id, text, message_type, status, agent_id, contact_id, registered_at, updated_at, sent_at, delivered_at, read_at, failed_at, deleted_at)
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::text[]),
    unnest($4::text[]),
    unnest($5::text[]),
    unnest($6::text[]),
    unnest($7::uuid[]),
    unnest($8::uuid[]),
    unnest($9::timestamptz[]),
    unnest($10::timestamptz[]),
    unnest($11::timestamptz[]),
    unnest($12::timestamptz[]),
    unnest($13::timestamptz[]),
    unnest($14::timestamptz[]),
    unnest($15::timestamptz[])
ON CONFLICT (id) DO UPDATE SET
    external_id = EXCLUDED.external_id,
    text = EXCLUDED.text,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at,
    sent_at = EXCLUDED.sent_at,
    delivered_at = EXCLUDED.delivered_at,
    read_at = EXCLUDED.read_at,
    failed_at = EXCLUDED.failed_at,
    deleted_at = EXCLUDED.deleted_at
`

type BatchUpsertMessagesParams struct {
	Ids             []pgtype.UUID        `json:"ids"`
	ConversationIds []pgtype.UUID        `json:"conversation_ids"`
	ExternalIds     []string             `json:"external_ids"`
	Texts           []string             `json:"texts"`
	MessageTypes    []string             `json:"message_types"`
	Statuses        []string             `json:"statuses"`
	AgentIds        []pgtype.UUID        `json:"agent_ids"`
	ContactIds      []pgtype.UUID        `json:"contact_ids"`
	RegisteredAts   []pgtype.Timestamptz `json:"registered_ats"`
	UpdatedAts      []pgtype.Timestamptz `json:"updated_ats"`
	SentAts         []pgtype.Timestamptz `json:"sent_ats"`
	DeliveredAts    []pgtype.Timestamptz `json:"delivered_ats"`
	ReadAts         []pgtype.Timestamptz `json:"read_ats"`
	FailedAts       []pgtype.Timestamptz `json:"failed_ats"`
	DeletedAts      []pgtype.Timestamptz `json:"deleted_ats"`
}

func (q *Queries) BatchUpsertMessages(ctx context.Context, arg BatchUpsertMessagesParams) error {
	_, err := q.db.Exec(ctx, batchUpsertMessages,
		arg.Ids,
		arg.ConversationIds,
		arg.ExternalIds,
		arg.Texts,
		arg.MessageTypes,
		arg.Statuses,
		arg.AgentIds,
		arg.ContactIds,
		arg.RegisteredAts,
		arg.UpdatedAts,
		arg.SentAts,
		arg.DeliveredAts,
		arg.ReadAts,
		arg.FailedAts,
		arg.DeletedAts,
	)
	return err
}

const findConversationByID = `-- name: FindConversationByID :many
SELECT
    c.id, c.status, c.unread_count, c.agent_id, c.contact_id, c.created_at, c.updated_at, c.finished_at,
    m.id, m.conversation_id, m.external_id, m.text, m.message_type, m.status, m.agent_id, m.contact_id, m.registered_at, m.updated_at, m.deleted_at, m.read_at, m.sent_at, m.delivered_at, m.failed_at
FROM conversations c
JOIN messages m ON m.conversation_id = c.id
WHERE c.id = $1
ORDER BY m.registered_at
`

type FindConversationByIDRow struct {
	Conversation Conversation `json:"conversation"`
	Message      Message      `json:"message"`
}

func (q *Queries) FindConversationByID(ctx context.Context, id pgtype.UUID) ([]FindConversationByIDRow, error) {
	rows, err := q.db.Query(ctx, findConversationByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindConversationByIDRow{}
	for rows.Next() {
		var i FindConversationByIDRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.Status,
			&i.Conversation.UnreadCount,
			&i.Conversation.AgentID,
			&i.Conversation.ContactID,
			&i.Conversation.CreatedAt,
			&i.Conversation.UpdatedAt,
			&i.Conversation.FinishedAt,
			&i.Message.ID,
			&i.Message.ConversationID,
			&i.Message.ExternalID,
			&i.Message.Text,
			&i.Message.MessageType,
			&i.Message.Status,
			&i.Message.AgentID,
			&i.Message.ContactID,
			&i.Message.RegisteredAt,
			&i.Message.UpdatedAt,
			&i.Message.DeletedAt,
			&i.Message.ReadAt,
			&i.Message.SentAt,
			&i.Message.DeliveredAt,
			&i.Message.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLastOpenConversationByContactID = `-- name: FindLastOpenConversationByContactID :many
SELECT
    c.id, c.status, c.unread_count, c.agent_id, c.contact_id, c.created_at, c.updated_at, c.finished_at,
    m.id, m.conversation_id, m.external_id, m.text, m.message_type, m.status, m.agent_id, m.contact_id, m.registered_at, m.updated_at, m.deleted_at, m.read_at, m.sent_at, m.delivered_at, m.failed_at
FROM conversations c
JOIN messages m ON m.conversation_id = c.id
WHERE c.contact_id = $1
  AND (c.status NOT IN ('expired', 'resolved') OR c.finished_at > now())
ORDER BY c.created_at DESC, m.registered_at
`

type FindLastOpenConversationByContactIDRow struct {
	Conversation Conversation `json:"conversation"`
	Message      Message      `json:"message"`
}

func (q *Queries) FindLastOpenConversationByContactID(ctx context.Context, contactID pgtype.UUID) ([]FindLastOpenConversationByContactIDRow, error) {
	rows, err := q.db.Query(ctx, findLastOpenConversationByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindLastOpenConversationByContactIDRow{}
	for rows.Next() {
		var i FindLastOpenConversationByContactIDRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.Status,
			&i.Conversation.UnreadCount,
			&i.Conversation.AgentID,
			&i.Conversation.ContactID,
			&i.Conversation.CreatedAt,
			&i.Conversation.UpdatedAt,
			&i.Conversation.FinishedAt,
			&i.Message.ID,
			&i.Message.ConversationID,
			&i.Message.ExternalID,
			&i.Message.Text,
			&i.Message.MessageType,
			&i.Message.Status,
			&i.Message.AgentID,
			&i.Message.ContactID,
			&i.Message.RegisteredAt,
			&i.Message.UpdatedAt,
			&i.Message.DeletedAt,
			&i.Message.ReadAt,
			&i.Message.SentAt,
			&i.Message.DeliveredAt,
			&i.Message.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWithSpecificMessageByExternalID = `-- name: FindWithSpecificMessageByExternalID :one
SELECT
    c.id, c.status, c.unread_count, c.agent_id, c.contact_id, c.created_at, c.updated_at, c.finished_at,
    m.id, m.conversation_id, m.external_id, m.text, m.message_type, m.status, m.agent_id, m.contact_id, m.registered_at, m.updated_at, m.deleted_at, m.read_at, m.sent_at, m.delivered_at, m.failed_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.external_id = $1
`

type FindWithSpecificMessageByExternalIDRow struct {
	Conversation Conversation `json:"conversation"`
	Message      Message      `json:"message"`
}

func (q *Queries) FindWithSpecificMessageByExternalID(ctx context.Context, externalID pgtype.Text) (FindWithSpecificMessageByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, findWithSpecificMessageByExternalID, externalID)
	var i FindWithSpecificMessageByExternalIDRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.Status,
		&i.Conversation.UnreadCount,
		&i.Conversation.AgentID,
		&i.Conversation.ContactID,
		&i.Conversation.CreatedAt,
		&i.Conversation.UpdatedAt,
		&i.Conversation.FinishedAt,
		&i.Message.ID,
		&i.Message.ConversationID,
		&i.Message.ExternalID,
		&i.Message.Text,
		&i.Message.MessageType,
		&i.Message.Status,
		&i.Message.AgentID,
		&i.Message.ContactID,
		&i.Message.RegisteredAt,
		&i.Message.UpdatedAt,
		&i.Message.DeletedAt,
		&i.Message.ReadAt,
		&i.Message.SentAt,
		&i.Message.DeliveredAt,
		&i.Message.FailedAt,
	)
	return i, err
}

const findWithSpecificMessageByMessageID = `-- name: FindWithSpecificMessageByMessageID :one
SELECT
    c.id, c.status, c.unread_count, c.agent_id, c.contact_id, c.created_at, c.updated_at, c.finished_at,
    m.id, m.conversation_id, m.external_id, m.text, m.message_type, m.status, m.agent_id, m.contact_id, m.registered_at, m.updated_at, m.deleted_at, m.read_at, m.sent_at, m.delivered_at, m.failed_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE m.id = $1
`

type FindWithSpecificMessageByMessageIDRow struct {
	Conversation Conversation `json:"conversation"`
	Message      Message      `json:"message"`
}

func (q *Queries) FindWithSpecificMessageByMessageID(ctx context.Context, messageID pgtype.UUID) (FindWithSpecificMessageByMessageIDRow, error) {
	row := q.db.QueryRow(ctx, findWithSpecificMessageByMessageID, messageID)
	var i FindWithSpecificMessageByMessageIDRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.Status,
		&i.Conversation.UnreadCount,
		&i.Conversation.AgentID,
		&i.Conversation.ContactID,
		&i.Conversation.CreatedAt,
		&i.Conversation.UpdatedAt,
		&i.Conversation.FinishedAt,
		&i.Message.ID,
		&i.Message.ConversationID,
		&i.Message.ExternalID,
		&i.Message.Text,
		&i.Message.MessageType,
		&i.Message.Status,
		&i.Message.AgentID,
		&i.Message.ContactID,
		&i.Message.RegisteredAt,
		&i.Message.UpdatedAt,
		&i.Message.DeletedAt,
		&i.Message.ReadAt,
		&i.Message.SentAt,
		&i.Message.DeliveredAt,
		&i.Message.FailedAt,
	)
	return i, err
}

const upsertConversation = `-- name: UpsertConversation :exec
INSERT INTO conversations (id, status, unread_count, agent_id, contact_id, created_at, updated_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    unread_count = EXCLUDED.unread_count,
    agent_id = EXCLUDED.agent_id,
    updated_at = EXCLUDED.updated_at,
    finished_at = EXCLUDED.finished_at
`

type UpsertConversationParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	UnreadCount int16              `json:"unread_count"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.Exec(ctx, upsertConversation,
		arg.ID,
		arg.Status,
		arg.UnreadCount,
		arg.AgentID,
		arg.ContactID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	return err
}
