// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Agent struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID                uuid.UUID          `json:"id"`
	ExternalContactID string             `json:"external_contact_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	UnreadCount int16              `json:"unread_count"`
	AgentID     uuid.UUID          `json:"agent_id"`
	ContactID   uuid.UUID          `json:"contact_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	ExternalID     pgtype.Text        `json:"external_id"`
	Text           string             `json:"text"`
	MessageType    string             `json:"message_type"`
	Status         string             `json:"status"`
	AgentID        uuid.UUID          `json:"agent_id"`
	ContactID      uuid.UUID          `json:"contact_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}
