// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID                pgtype.UUID
	ExternalContactID string
	CreatedAt         pgtype.Timestamptz
}

type Conversation struct {
	ID            pgtype.UUID
	Status        string
	UserID        pgtype.UUID
	ContactID     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	LastMessageAt pgtype.Timestamptz
	LastMessageID pgtype.UUID
	UnreadCount   int32
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Status         string
	Type           string
	Text           *string
	UserID         pgtype.UUID
	ContactID      pgtype.UUID
	ExternalID     *string
	SentAt         pgtype.Timestamptz
	ReadAt         pgtype.Timestamptz
	EditedAt       pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
