// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_information.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPersonalInformationByID = `-- name: FindPersonalInformationByID :one
SELECT id, identification_number, first_name, last_name, phone_number, email, address, created_at, updated_at
FROM personal_information
WHERE id = $1
`

func (q *Queries) FindPersonalInformationByID(ctx context.Context, id pgtype.UUID) (PersonalInformation, error) {
	row := q.db.QueryRow(ctx, findPersonalInformationByID, id)
	var i PersonalInformation
	err := row.Scan(
		&i.ID,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPersonalInformationByIdentificationNumber = `-- name: FindPersonalInformationByIdentificationNumber :one
SELECT id, identification_number, first_name, last_name, phone_number, email, address, created_at, updated_at
FROM personal_information
WHERE identification_number = $1
`

func (q *Queries) FindPersonalInformationByIdentificationNumber(ctx context.Context, identificationNumber string) (PersonalInformation, error) {
	row := q.db.QueryRow(ctx, findPersonalInformationByIdentificationNumber, identificationNumber)
	var i PersonalInformation
	err := row.Scan(
		&i.ID,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPersonalInformation = `-- name: UpsertPersonalInformation :one
INSERT INTO personal_information (
    id, identification_number, first_name, last_name, phone_number, email, address, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (identification_number) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone_number = EXCLUDED.phone_number,
    email = EXCLUDED.email,
    address = EXCLUDED.address,
    updated_at = EXCLUDED.updated_at
RETURNING id, identification_number, first_name, last_name, phone_number, email, address, created_at, updated_at
`

type UpsertPersonalInformationParams struct {
	ID                   pgtype.UUID
	IdentificationNumber string
	FirstName            *string
	LastName             *string
	PhoneNumber          *string
	Email                *string
	Address              *string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) UpsertPersonalInformation(ctx context.Context, arg UpsertPersonalInformationParams) (PersonalInformation, error) {
	row := q.db.QueryRow(ctx, upsertPersonalInformation,
		arg.ID,
		arg.IdentificationNumber,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.Email,
		arg.Address,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PersonalInformation
	err := row.Scan(
		&i.ID,
		&i.IdentificationNumber,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
